### ISSUE TITLE
Soulstone Bugged

### ISSUE THREAD

**Issue by jacatinelord** [silviu20092/azerothcore-reforging#1]
After adding the module, players cant use soulstone.
Sometime player cant cast it, sometime the effect on the soulstone did not show on the self cast.

**Comment by jacatinelord** [comment]
maybe instead of checking all item in the inventory/bag, check only with the InventoryType or ItemClass

**Comment by silviu20092** [comment]
Not related to reforging in any way

**Comment by jacatinelord** [comment]
fortunately this was related to reforging. By removing the module, the use of soulstone is back to normal.
also to mention, quest item that castable sometimes will not working too.

not sure how to replicate this, because i had 30-40 ppl playing and random characters are experiencing them. Sometimes it can effect old characters, or new characters.

but since its a source code available, i will try find a fix for it anyway. thanks for making the module.
